---
ccm_hc:
  - name: "Accounts: Limit local account use of blank passwords to console logon only"
    ref: "2.3.1.4"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -Name LimitBlankPasswordUse) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Audit: Shut down system immediately if unable to log security audits"
    ref: "2.3.2.2"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -Name CrashOnAuditFail) {Write-Output "KO"} else {Write-Output "OK"}'

  #There is a GAP here as registry value is not found for 2.3.4.1

  - name: "Devices: Prevent users from installing printer drivers"
    ref: "2.3.4.2"
    action: 'if (Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers\" -Name AddPrinterDrivers) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Domain member: Digitally encrypt or sign secure channel data (always)"
    ref: "2.3.6.1"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters -Name RequireSignOrSeal) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Domain member: Digitally encrypt secure channel data (when possible)"
    ref: "2.3.6.2"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name SealSecureChannel) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Domain member: Digitally sign secure channel data (when possible)"
    ref: "2.3.6.3"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name SignSecureChannel) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Domain member: Disable machine account password changes"
    ref: "2.3.6.4"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name DisablePasswordChange) {Write-Output "KO"} else {Write-Output "OK"}'
  
  - name: "Domain member: Maximum machine account password age"
    ref: "2.3.6.5"
    action: 'if (((Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name MaximumPasswordAge) -ne 0) -and ((Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name MaximumPasswordAge) -le 30)) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Domain member: Require strong (Windows 2000 or later) session key"
    ref: "2.3.6.6"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\ -Name RequireStrongKey) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Interactive logon: Prompt user to change password before expiration"
    ref: "2.3.7.7"
    action: 'if (((Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name PasswordExpiryWarning) -ge 5) -and ((Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name PasswordExpiryWarning) -le 14)) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Microsoft network client: Digitally sign communications (if server agrees)"
    ref: "2.3.8.2"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name EnableSecuritySignature) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Microsoft network client: Send unencrypted password to third-party SMB servers"
    ref: "2.3.8.3"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name EnablePlainTextPassword) {Write-Output "KO"} else {Write-Output "OK"}'

  - name: "Microsoft network server: Amount of idle time required before suspending session"
    ref: "2.3.9.1"
    action: 'if (((Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ -Name AutoDisconnect) -ne 0) -and ((Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ -Name AutoDisconnect) -le 15)) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Microsoft network server: Disconnect clients when logon hours expire"
    ref: "2.3.9.4"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\ -Name EnableForcedLogoff) {Write-Output "OK"} else {Write-Output "KO"}'

  #There is a GAP here as registry value is not found for 2.3.10.1

  - name: "Network access: Do not allow anonymous enumeration of SAM accounts"
    ref: "2.3.10.2"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\ -Name RestrictAnonymousSAM) {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Network access: Let Everyone permissions apply to anonymous users"
    ref: "2.3.10.5"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\ -Name EveryoneIncludesAnonymous) {Write-Output "KO"} else {Write-Output "OK"}'

  - name: "Network access: Remotely accessible registry paths"
    ref: "2.3.10.7"
    action: 'if (-not (Compare-Object (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\winreg\AllowedExactPaths\ -Name Machine) "System\CurrentControlSet\Control\ProductOptions", "System\CurrentControlSet\Control\Server Applications", "Software\Microsoft\Windows NT\CurrentVersion"))  {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Network access: Remotely accessible registry paths and sub-paths"
    ref: "2.3.10.8"
    action: 'if (-not (Compare-Object (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\winreg\AllowedPaths\ -Name Machine) "System\CurrentControlSet\Control\Print\Printers", "System\CurrentControlSet\Services\Eventlog", "Software\Microsoft\OLAP Server", "Software\Microsoft\Windows NT\CurrentVersion\Print", "Software\Microsoft\Windows NT\CurrentVersion\Windows", "System\CurrentControlSet\Control\ContentIndex", "System\CurrentControlSet\Control\Terminal Server", "System\CurrentControlSet\Control\Terminal Server\UserConfig", "System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration", "Software\Microsoft\Windows NT\CurrentVersion\Perflib", "System\CurrentControlSet\Services\SysmonLog"))  {Write-Output "OK"} else {Write-Output "KO"}'

  - name: "Network access: Restrict anonymous access to Named Pipes and Shares"
    ref: "2.3.10.9"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters -Name RestrictNullSessAccess) {Write-Output "OK"} else {Write-Output "KO"}'

  #Note: The BoI agreed value is "Classic - local users authenticate as themselves". In the registry that is the 0 value.
  - name: "Network access: Sharing and security model for local accounts"
    ref: "2.3.10.11"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Control\Lsa -Name ForceGuest) {Write-Output "KO"} else {Write-Output "OK"}'

  #There is a GAP here as registry value is not found for 2.3.11.2"

  #There is a GAP here as registry value is not found for 2.3.11.3"

  - name: "Network security: Force logoff when logon hours expire"
    ref: "2.3.11.6"
    action: 'if (Get-ItemPropertyValue -Path HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters\ -Name EnableForcedLogOff) {Write-Output "OK"} else {Write-Output "KO"}'

  #There is a GAP here as registry value is not found for 2.3.11.8. The values are numerical, but the agreed-upon values are certain strings."